### ISSUE TITLE
Open Source up-to-date EPUB3 library/SDK?

### ISSUE THREAD

**Issue by timofonic** [IDPF/epub-revision#641]
Hello.

Are there some Open Source and up-to-date reference EPUB3 library/SDK? Readium seems not so popular, an official and easy to use obe woukld skyrocket the adoption of this standard.

Please consider MathML and an agnostic format to represent electronic schematics. This would make epub3 better for technical ebooks.

**Comment by mattgarrish** [comment]
This issue tracker is for bugs and feature requests for the epub specifications. If you have general support questions, please try the idpf forms at http://www.idpf.org/forums
